# Generated by Django 6.0 on 2025-12-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couse_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question_text',
            new_name='question_title',
        ),
    ]
