# Generated by Django 6.0 on 2026-01-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couse_app', '0003_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_course', to='couse_app.course'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_question', to='couse_app.questions'),
        ),
    ]
